apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kube-cards-website.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "kube-cards-website.name" . }}
    helm.sh/chart: {{ include "kube-cards-website.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
stringData:
  msalAuthority: {{ .Values.secrets.msalAuthority }}
  msalClientId: {{ .Values.secrets.msalClientId }}
  msalImpersonationScope: {{ .Values.secrets.msalImpersonationScope }}
  cardsInventoryServiceBaseUri: {{ .Values.secrets.cardsInventoryServiceBaseUri }}
