apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kube-cards-decks-service.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "kube-cards-decks-service.name" . }}
    helm.sh/chart: {{ include "kube-cards-decks-service.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
stringData:
  environment: {{ .Values.secrets.environment }}
  b2cInstance: {{ .Values.secrets.b2cInstance }}
  b2cClientId: {{ .Values.secrets.b2cClientId }}
  b2cDomain: {{ .Values.secrets.b2cDomain }}
  b2cSignUpSignInPolicyId: {{ .Values.secrets.b2cSignUpSignInPolicyId }}
  cardsDbConnectionString: {{ .Values.secrets.cardsDbConnectionString }}