{{- $fullName := include "kube-cards-ingress.fullname" . -}}
{{- $websiteName := include "kube-cards-ingress.website.name" . -}}
{{- $decksServiceName := include "kube-cards-ingress.decks-service.name" . -}}
{{- $inventoryServiceName := include "kube-cards-ingress.inventory-service.name" . -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    app.kubernetes.io/name: {{ include "kube-cards-ingress.name" . }}
    helm.sh/chart: {{ include "kube-cards-ingress.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: 'true'
    certmanager.k8s.io/cluster-issuer: {{ .Values.ingress.issuer }}
  {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
{{- if .Values.ingress.tls }}
  tls:
  {{- range .Values.ingress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . | quote }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  rules:
    - host: {{ .Values.ingress.host | quote }}
      http:
        paths:
          - path: /api/cards
            backend:
              serviceName: {{ $inventoryServiceName }}
              servicePort: http
          - path: /api/decks
            backend:
              serviceName: {{ $decksServiceName }}
              servicePort: http
          - path: /
            backend:
              serviceName: {{ $websiteName }}
              servicePort: http
